[package]
name = "chip_8"
version = "0.1.0"
authors = ["gumba"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.3" 
rand = "0.3.14"
regex = "1"